# https://docs.travis-ci.com/user/languages/android
language: android

jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-google-analytics_sdk_v2
  - extra-google-admob_ads_sdk

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script: "./gradlew build connectedCheck --no-daemon --stacktrace"

sudo: required

deploy:
  provider: releases
  api_key:
    secure: r3MsgbpEsYrHnp9Wqk4qJYbUEtxLbyqdR3EoOSkSYboaESUJvH40HsxQRJQYwxYcQgYT2ZJMOoZMQ7QdbNvvVD36jpF/p3TKy006y2jtC/QdG/s7TXNoUCWHJ4zm4bH4+1Sn9mw/9GwaIlWo72/35IFXUrR3P1+sZY0XukTTMqzTB178ae7HzRZlceg6UaUJGNYH3a/WZmvtHjEva8o5a2GCFbWQKFp7cNYpCETvil8ilHWzrOnYUbw+jne6DinUy8hNvD0r/o9R810QXhXB5QaEXQcDcw8iBHl4ZrQkyKbsIINUcU8aE0qKpDB+PpMWsCDfVcJSLTfaG61HK0i3S50KwQyDRvnALNYYgSMxZKtPpZHOOqFQgTCdn23JX4hv+wZUVyTp2xqJ/MVJE7oYjHI7ec+fi2udP5X+zKGDqMZMu8PwpRKNftAUT6XoGlb5OFG3tFxnO5PL43tBeF8C0QggYtDQiHu9oxrwFdVoXM6DYN+w3uZVVXGpyzRl8wjwhtZIA8Llg2G/9M6ZHPtFJnb41yumCsA8JNO/icI/I/SkSj9XuAXV3Uof5XN0yPEHJVqamD2MgBtMXbV/TPgx061rSRRZCj+rVXSKfHs86Jzob1kglRiD/Hj8wVHIhJAQXbuUgXg9pjxOkkRVzR/b+HpYZtG0DENfUqEFkGQbzqQ=
  file: "./attendance/build/outputs/apk/attendance-release.apk"
  skip_cleanup: true
  on:
    tags: true
    branch: release

after_deploy: "./gradlew publishRelease --no-daemon --stacktrace"

