language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-google-analytics_sdk_v2
  - extra-google-admob_ads_sdk
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew assembleDebug connectedCheck --no-daemon --stacktrace; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./gradlew build connectedCheck --no-daemon --stacktrace; fi'
sudo: false
deploy:
  provider: releases
  api_key:
    secure: zmOEqC6xjAeq1s00Vfvuva1vPw3PGZrrNTz/yJwP5Cs2wOgLvSRbe1hJHqYvjyKdoqm2yhNdTTm+xQCv9tFa8+dW+5h2xwhERYywt4UdMa4bMMcGX18jqCTWjz4x73pEfv+xl1y+7nyW7chqL0HE73CJczlnkuq2KEiiIIHAmS+PMdJ+0jm7Bg901KMCjKixccNmUtD5E7S2ZJqgJg99VwrWeYG3xitcvn0x+Y2C3MuHgKIoPYp4DAQC7Y7sIYukj1jN+rIhorY4MIAf4rnZruli+AXs9pAhPzyqtMnrNArM5IXp9q29CR32uIjNNYAGIQWLOfMyjnel0VqlesXRGzaC/+UeWJwN92rGgaS+GbkNzFpRC5bdYAjnEO2Lo/DVZoNCSgOjXHgbZegTp0ZF76XJv1ZBol1PFbKl9/Sf1XORfTkYuP6e86pEvNvMcgS11xVrhZNAk8aNLQ3ZKxzkBksINuBr03v9zXwwtFzBlklNw0YD75QzFhMyBCZgfKRmVfWjsqFyCkjdo7BWAKEm+8dn6Xtu2L9N0KXf8X9YL43UihYZ8SRiLT8sn9gxLsDiMCvM5jwnrlWUT8yXP0qw9yRssep6phP0iq2WmMHh+ZBVrxPGPu+bfdMccAGoEMFsfH8wLFrpl5vTLy0C7F4Q7RsXOWrVGTpAckPdDG9GhmY=
  file: "./attendance/build/outputs/apk/attendance-release.apk"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: Shalzz/upes-academics
after_deploy: "./gradlew publishRelease --no-daemon --stacktrace"
env:
  secure: 07OFO7sZRirr9ZxcxXN6Q3RgXCla0zeSGSFGP0BKx0ssgw1RGOBNnB1wiN0Jh3iO05RIMrT3MxKtk7/b1K/r0HB0oqBKchbAnF6mufmvOerY8NxADXBL1t5zrn6NfkfafPeHsM6dFl1vLDzZWtFxtphE1KfsuhUMWzW1nDg8inCvdUp9BXp+Rpf99TE0gVBzi6VSzGtYeB6CQuWOZAHCj/SPXNHH7azolnIuhEtp1luws/tfvigFatvuTY4aPYcGY1tzH1Qby3rN1oOvSQKDULLUWsGQTb+wWT/SIxlHCwxJrLZ8HGw5VMqlSN9Q/K1rweg3wUHkTLdf9eMp3wb7K+x1TY4WpF1FYGfi/m4lIiOojDjssuo0l0qOxQ/Ko1EpornyX4C0JnnnSKf+3QI/HKBKJfulvUQLsAnWb50ZSZQvcrbhrYY3p4VTZ9MFUaDBBo8QEY/ld1Pnq42gOJGdWgFJMQPACKO3p+bhQNgiG20l7rIdQRIvboKYpC4Q2JlzeWxkA3/ZUQks+akuEgGgb8wr8F0qLO7GxeQEHK1rs1ryhyDHjA9M7BCfArlTR3pD44BosCwAJrgqnqVTZUaCa8g71QvDk7z+iJ+57IK5TyS43W3uyC5x0N8g1prtc3mBJ3sA6ibIlWxdULAsWcIpy0WL0yzQpXw4t3mdZeQB3b8=
before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_ef2e0b3750f6_key -iv $encrypted_ef2e0b3750f6_iv -in 
play-service-account-key.json.enc -out play-service-account-key.json -d; fi'
