language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-google-analytics_sdk_v2
  - extra-google-admob_ads_sdk
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: "./gradlew build connectedCheck --no-daemon --stacktrace"
sudo: false
deploy:
  provider: releases
  api_key:
    secure: r3MsgbpEsYrHnp9Wqk4qJYbUEtxLbyqdR3EoOSkSYboaESUJvH40HsxQRJQYwxYcQgYT2ZJMOoZMQ7QdbNvvVD36jpF/p3TKy006y2jtC/QdG/s7TXNoUCWHJ4zm4bH4+1Sn9mw/9GwaIlWo72/35IFXUrR3P1+sZY0XukTTMqzTB178ae7HzRZlceg6UaUJGNYH3a/WZmvtHjEva8o5a2GCFbWQKFp7cNYpCETvil8ilHWzrOnYUbw+jne6DinUy8hNvD0r/o9R810QXhXB5QaEXQcDcw8iBHl4ZrQkyKbsIINUcU8aE0qKpDB+PpMWsCDfVcJSLTfaG61HK0i3S50KwQyDRvnALNYYgSMxZKtPpZHOOqFQgTCdn23JX4hv+wZUVyTp2xqJ/MVJE7oYjHI7ec+fi2udP5X+zKGDqMZMu8PwpRKNftAUT6XoGlb5OFG3tFxnO5PL43tBeF8C0QggYtDQiHu9oxrwFdVoXM6DYN+w3uZVVXGpyzRl8wjwhtZIA8Llg2G/9M6ZHPtFJnb41yumCsA8JNO/icI/I/SkSj9XuAXV3Uof5XN0yPEHJVqamD2MgBtMXbV/TPgx061rSRRZCj+rVXSKfHs86Jzob1kglRiD/Hj8wVHIhJAQXbuUgXg9pjxOkkRVzR/b+HpYZtG0DENfUqEFkGQbzqQ=
  file: "./attendance/build/outputs/apk/attendance-release.apk"
  skip_cleanup: true
  on:
    tags: true
    branch: release
after_deploy: "./gradlew publishRelease --no-daemon --stacktrace"
env:
  secure: 07OFO7sZRirr9ZxcxXN6Q3RgXCla0zeSGSFGP0BKx0ssgw1RGOBNnB1wiN0Jh3iO05RIMrT3MxKtk7/b1K/r0HB0oqBKchbAnF6mufmvOerY8NxADXBL1t5zrn6NfkfafPeHsM6dFl1vLDzZWtFxtphE1KfsuhUMWzW1nDg8inCvdUp9BXp+Rpf99TE0gVBzi6VSzGtYeB6CQuWOZAHCj/SPXNHH7azolnIuhEtp1luws/tfvigFatvuTY4aPYcGY1tzH1Qby3rN1oOvSQKDULLUWsGQTb+wWT/SIxlHCwxJrLZ8HGw5VMqlSN9Q/K1rweg3wUHkTLdf9eMp3wb7K+x1TY4WpF1FYGfi/m4lIiOojDjssuo0l0qOxQ/Ko1EpornyX4C0JnnnSKf+3QI/HKBKJfulvUQLsAnWb50ZSZQvcrbhrYY3p4VTZ9MFUaDBBo8QEY/ld1Pnq42gOJGdWgFJMQPACKO3p+bhQNgiG20l7rIdQRIvboKYpC4Q2JlzeWxkA3/ZUQks+akuEgGgb8wr8F0qLO7GxeQEHK1rs1ryhyDHjA9M7BCfArlTR3pD44BosCwAJrgqnqVTZUaCa8g71QvDk7z+iJ+57IK5TyS43W3uyC5x0N8g1prtc3mBJ3sA6ibIlWxdULAsWcIpy0WL0yzQpXw4t3mdZeQB3b8=
before_install:
- openssl aes-256-cbc -K $encrypted_ef2e0b3750f6_key -iv $encrypted_ef2e0b3750f6_iv
  -in play-service-account-key.json.enc -out play-service-account-key.json -d
